/**
 * Webhook Routes
 * Handles incoming Shopify webhooks for draft orders and orders
 */

const express = require('express');
const router = express.Router();
const shopifyService = require('../services/shopify');
const invoiceService = require('../services/invoice');

/**
 * Webhook signature verification middleware
 */
const verifyWebhook = (req, res, next) => {
  const hmac = req.get('X-Shopify-Hmac-Sha256');
  
  if (!hmac) {
    console.warn('Webhook received without HMAC signature');
    // In development, allow unsigned webhooks
    if (process.env.NODE_ENV === 'development') {
      return next();
    }
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    const body = req.body.toString('utf8');
    const isValid = shopifyService.verifyWebhookSignature(body, hmac);
    
    if (!isValid) {
      console.warn('Invalid webhook signature');
      return res.status(401).json({ error: 'Invalid signature' });
    }
    
    // Parse the body for downstream handlers
    req.webhookData = JSON.parse(body);
    next();
  } catch (error) {
    console.error('Webhook verification error:', error);
    res.status(401).json({ error: 'Verification failed' });
  }
};

// Apply verification to all webhook routes
router.use(verifyWebhook);

/**
 * Log webhook receipt
 */
const logWebhook = (topic, data) => {
  console.log(`
═══════════════════════════════════════════════════════
WEBHOOK RECEIVED: ${topic}
Time: ${new Date().toISOString()}
ID: ${data.id || 'N/A'}
═══════════════════════════════════════════════════════
  `);
};

/**
 * Draft Order Created webhook
 */
router.post('/draft_orders-create', async (req, res) => {
  const draftOrder = req.webhookData;
  logWebhook('draft_orders/create', draftOrder);

  try {
    // Store webhook event for tracking
    console.log('New draft order created:', {
      id: draftOrder.id,
      name: draftOrder.name,
      customer: draftOrder.customer?.email,
      total: draftOrder.total_price
    });

    // Optionally auto-generate invoice preview
    // const invoiceData = invoiceService.draftOrderToInvoice(draftOrder);
    // console.log('Invoice preview ready:', invoiceData.invoiceNumber);

    res.status(200).json({ received: true });
  } catch (error) {
    console.error('Error processing draft_orders/create:', error);
    res.status(200).json({ received: true, error: error.message });
  }
});

/**
 * Draft Order Updated webhook
 */
router.post('/draft_orders-update', async (req, res) => {
  const draftOrder = req.webhookData;
  logWebhook('draft_orders/update', draftOrder);

  try {
    console.log('Draft order updated:', {
      id: draftOrder.id,
      name: draftOrder.name,
      status: draftOrder.status,
      total: draftOrder.total_price
    });

    // Check if draft order was completed (converted to order)
    if (draftOrder.status === 'completed' && draftOrder.order_id) {
      console.log('Draft order completed! Order ID:', draftOrder.order_id);
      
      // Auto-generate invoice for completed orders
      const invoiceData = invoiceService.draftOrderToInvoice(draftOrder);
      const pdfResult = await invoiceService.generatePDF(invoiceData);
      
      console.log('Auto-generated invoice:', {
        invoiceNumber: invoiceData.invoiceNumber,
        pdf: pdfResult.filename
      });

      // Store invoice metadata on the order
      try {
        await shopifyService.createOrderMetafield(draftOrder.order_id, {
          invoiceNumber: invoiceData.invoiceNumber,
          createdAt: invoiceData.createdAt,
          pdfFile: pdfResult.filename,
          autoGenerated: true
        });
      } catch (metaError) {
        console.error('Failed to store invoice metadata:', metaError.message);
      }
    }

    res.status(200).json({ received: true });
  } catch (error) {
    console.error('Error processing draft_orders/update:', error);
    res.status(200).json({ received: true, error: error.message });
  }
});

/**
 * Draft Order Deleted webhook
 */
router.post('/draft_orders-delete', async (req, res) => {
  const draftOrder = req.webhookData;
  logWebhook('draft_orders/delete', draftOrder);

  try {
    console.log('Draft order deleted:', draftOrder.id);
    
    // Clean up any generated invoices if needed
    // Note: You may want to keep invoices for record-keeping

    res.status(200).json({ received: true });
  } catch (error) {
    console.error('Error processing draft_orders/delete:', error);
    res.status(200).json({ received: true, error: error.message });
  }
});

/**
 * Order Created webhook
 */
router.post('/orders-create', async (req, res) => {
  const order = req.webhookData;
  logWebhook('orders/create', order);

  try {
    console.log('New order created:', {
      id: order.id,
      name: order.name,
      customer: order.customer?.email,
      total: order.total_price,
      financialStatus: order.financial_status
    });

    // If order came from a draft order, the invoice should already exist
    // Otherwise, you might want to generate one

    res.status(200).json({ received: true });
  } catch (error) {
    console.error('Error processing orders/create:', error);
    res.status(200).json({ received: true, error: error.message });
  }
});

/**
 * Order Paid webhook
 */
router.post('/orders-paid', async (req, res) => {
  const order = req.webhookData;
  logWebhook('orders/paid', order);

  try {
    console.log('Order paid:', {
      id: order.id,
      name: order.name,
      total: order.total_price
    });

    // Update invoice status to paid
    // You could integrate with your accounting system here
    // Or send a payment confirmation email

    res.status(200).json({ received: true });
  } catch (error) {
    console.error('Error processing orders/paid:', error);
    res.status(200).json({ received: true, error: error.message });
  }
});

/**
 * Order Fulfilled webhook
 */
router.post('/orders-fulfilled', async (req, res) => {
  const order = req.webhookData;
  logWebhook('orders/fulfilled', order);

  try {
    console.log('Order fulfilled:', {
      id: order.id,
      name: order.name,
      fulfillmentStatus: order.fulfillment_status
    });

    // Send shipping confirmation
    // Update CRM or accounting system
    // Generate shipping invoice if separate from initial invoice

    res.status(200).json({ received: true });
  } catch (error) {
    console.error('Error processing orders/fulfilled:', error);
    res.status(200).json({ received: true, error: error.message });
  }
});

/**
 * Catch-all for unhandled webhook topics
 */
router.post('*', (req, res) => {
  const topic = req.path.replace('/', '').replace('-', '/');
  console.log(`Unhandled webhook topic: ${topic}`);
  res.status(200).json({ received: true, handled: false });
});

module.exports = router;
